### ISSUE TITLE
Se renseigner sur Substrate

### ISSUE THREAD

**Issue by arthurlejay** [ambula-labs/ambula#1]
Rechercher parmis les choses implémentées par Substrate celles qui correspondent aux objectifs.

**Comment by ybasri** [comment]
Voici le lien

**Comment by ybasri** [comment]
Voici le lien google docs des notes de mes recherche sur substrate. https://docs.google.com/document/d/1RuUdHoU96sOXgNN0fICXlYbqgMpZ-ROgw2ZHXqq4600/edit?usp=sharing.
NB: ce travail a été fait pour le front et il faudrait donc déplacer l'issue sur "Ambula explorer".
