### ISSUE TITLE
Setup a custom RPC service that answers signature requests on network nodes

### ISSUE THREAD

**Issue by arthurlejay** [ambula-labs/ambula#11]
Setup a custom RPC service that answers signature requests on network nodes, at first it could be nice to simply answer "Hello World" from the PoW part of the algorithm
https://github.com/ambula-labs/ambula/blob/c5ea4f8575c65f8a479536b6961ae80cc5588831/nodes/basic-pow/src/service.rs#L252
https://substrate.recipes/custom-rpc.html
https://blog.knoldus.com/rpc-to-call-a-runtime-api-easily-in-substrate/

We don't care about "call a runtime API", we just want a custom RPC with our own logiq

**Comment by LcsTen** [comment]
It seems the linked tutorials are outdated. They refer to a class ``sc_rpc::Metadata`` which doesn't seem to exist anymore. Moreover, one of the tutorials says that we must use sc_rpc 3.0, while our current sc_rpc version is 4.0. I'm trying to implement https://substrate.stackexchange.com/a/5555.
