### ISSUE TITLE
Terminer le RESCRIT

### ISSUE THREAD

**Issue by 0xA1337** [ambula-labs/ambula#6]
Terminer et soumettre le RESCRIT à l'encadrant de matière.

**Comment by arthurlejay** [comment]
Lien partagé à l'enseignant il y a un mois de cela : 
[https://docs.google.com/document/d/12FaLIc7OCSX5bNJgEnAqPmEkbhDlkxnEPCnq0LjWnns/edit?usp=sharing](https://docs.google.com/document/d/12FaLIc7OCSX5bNJgEnAqPmEkbhDlkxnEPCnq0LjWnns/edit?usp=sharing)
